### PR TITLE
fix: quicksearch trigger on firefox

### PR DESCRIPTION
**Pull request by blackkspydo**

### CODE REVIEW

**Review by broisnischal — APPROVED** [review]
Good job! I didn't know this may cause an error in Firefox. anyway, it resolved well for us!

**Comment by broisnischal** [comment]
It created another bug :(

**Comment by blackkspydo** [comment]
> It created another bug :(

Create an issue, I'll help on it.

**Comment by broisnischal** [comment]
The preventDefault is, causing the issue, suppose if I try to reload it won't.  Also can write in the outer input, because of preventing!

Is there any way that you may fix this search trigger error in firefox without preventdefaulting the event?

**Comment by broisnischal** [comment]
I removed the preventDefault, it causing in other browsers. let's find out other method to fix in firefox !

**Pull request merged**
